name: rund
description: "Get places around you."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^11.0.0
  geolocator: ^11.1.0
  http: ^1.2.1
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  map_launcher: ^3.5.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/rund_logo.png"
