services:
  rund-backend:
    build: .
    image: rund
    container_name: rund-backend
    ports:
    - "8080:8080"
    - "443:443"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: rund
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    container_name: rund-db
    environment:
      POSTGRES_DB: rund
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - rund_db:/var/lib/postgresql/data
      - ./create-db-oapi.sh:/docker-entrypoint-initdb.d/create-db.sh

volumes:
  rund_db:
