version: '3.8'

services:
  autour-backend:
    build: .
    image: autour
    container_name: autour-backend
    ports:
    - "8080:8080"
    - "443:443"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: autour
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    container_name: autour-db
    environment:
      POSTGRES_DB: autour
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - autour_db:/var/lib/postgresql/data
      - ./create-db.sh:/docker-entrypoint-initdb.d/create-db.sh

volumes:
  autour_db:
