version: '3.8'
services:
  postgres:
    image: postgres
    container_name: autour-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - autour_db:/var/lib/postgresql/data

volumes:
  autour_db:
